export const skills = [
  "React",
  "Next.js",
  "TypeScript",
  "JavaScript",
  "Tailwind CSS",
  "Zustand",
  "React Query",
  "React Hook Form",
  "Zod",
  "React Flow",
  "Vite",
  "Turborepo",
  "pnpm",
  "Node.js",
  "PostgreSQL",
  "REST APIs",
  "WebSocket",
  "Web Audio API",
  "Vitest",
  "Storybook",
  "Sentry",
  "GitHub Actions",
  "shadcn/ui",
  "AG Grid",
  "Git",
] as const;
