import { IconArrowLeft } from "@tabler/icons-react";
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { SiteFooter } from "@/components/layout/site-footer";
import { SiteHeader } from "@/components/layout/site-header";
import { PortfolioDetail } from "@/components/portfolio/portfolio-detail";
import type { Locale } from "@/i18n/routing";
import { buildAlternates } from "@/lib/i18n/metadata";
import {
  getAllPublishedSlugs,
  getPortfolioBySlug,
} from "@/lib/queries/portfolio";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>;
}): Promise<Metadata> {
  const { locale, slug } = await params;
  const item = await getPortfolioBySlug(slug, locale as Locale);
  if (!item) return {};

  return {
    title: item.title,
    description: item.shortDescription,
    alternates: buildAlternates(locale as Locale, `/portfolio/${slug}`),
    openGraph: {
      title: item.title,
      description: item.shortDescription,
      // og image is auto-generated by opengraph-image.tsx in this segment
    },
  };
}

export async function generateStaticParams() {
  return getAllPublishedSlugs();
}

export default async function PortfolioPage({
  params,
}: {
  params: Promise<{ locale: string; slug: string }>;
}) {
  const { locale, slug } = await params;
  setRequestLocale(locale);

  const t = await getTranslations("detail");
  const item = await getPortfolioBySlug(slug, locale as Locale);
  if (!item) notFound();

  return (
    <>
      <SiteHeader />
      <main className="mx-auto max-w-3xl px-6 py-12">
        <Link
          href={`/${locale}/#portfolio`}
          className="mb-8 inline-flex items-center gap-1.5 text-sm text-muted-foreground transition-colors hover:text-foreground"
        >
          <IconArrowLeft className="size-4" />
          {t("backToPortfolio")}
        </Link>
        <PortfolioDetail item={item} />
      </main>
      <SiteFooter />
    </>
  );
}
